
.PHONY: all clean

all:
	$(MAKE) -C 1
	$(MAKE) -C 2
	$(MAKE) -C 3
	$(MAKE) -C 4
	$(MAKE) -C 5
	$(MAKE) -C 6
clean:
	$(MAKE) -C 1 clean
	$(MAKE) -C 2 clean
	$(MAKE) -C 3 clean
	$(MAKE) -C 4 clean
	$(MAKE) -C 5 clean
	$(MAKE) -C 6 clean